package day6;

import org.testng.annotations.Test;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.ObjectMapper;

public class SerializationDeSerialization {
	
	//Pojo to Json (Serialization)
	
	@Test(priority=1)	
	void convertPojo2Json() throws JsonProcessingException {
		
		//Created java object using pojo class
		
		Student stuPojo = new Student();  //pojo
		
		stuPojo.setName("Kishore");
		stuPojo.setJob("Student");
		
		//Convert java object to json object (Serialization)
		
		ObjectMapper objMapper = new ObjectMapper();  // import jackson.databind
		
		String jsonData = objMapper.writerWithDefaultPrettyPrinter().writeValueAsString(stuPojo);
		
		System.out.println(jsonData);	
	}
	
	
	//Json to Pojo (DeSerialization)
	
	@Test(priority=2)
	void convertJson2Pojo() throws JsonMappingException, JsonProcessingException {
		
		String jsonData = "{\r\n"
				+ "  \"name\" : \"Kishore\",\r\n"   //Automatically generated by Eclipse
				+ "  \"job\" : \"Student\"\r\n"
				+ "}";
		
		//Convert json object to pojo object (DeSerialization)
		
		ObjectMapper objMapper = new ObjectMapper();
		
		Student stuPojo = objMapper.readValue(jsonData,Student.class); //convert json to pojo
		
		System.out.println("Name: " + stuPojo.getName());
		System.out.println("Job: " + stuPojo.getJob());
		 
		
	}

}
